### ISSUE TITLE
about  USB-SSDT folder,thanks

### ISSUE THREAD

**Issue by Code-Fight** [cnrd/GA-Z170X-UD3-OSX#2]
thanks for your guide :http://www.tonymacx86.com/threads/guide-el-capitan-on-the-ga-z170x-ud3.180618/

but, i'm can't find some files,can you help me?thanks

in your guide:

**Prepare Installer**

  **12.Copy files from USB-SSDT folder to these places**
- ACPI/patched/SSDT-5.aml
- ACPI/patched/USB-SSDT.aml

i'm don't find  **USB-SSDT folder**  
thanks

**Comment by cnrd** [comment]
Go to the last section in the guide called: "Setup USB" it will help you generate the two files required.

I should probably rework that section as you are the 5. person to ask :-)

**Comment by Code-Fight** [comment]
thank you very much
